### ISSUE TITLE
koji wait-repo needs --request now

### ISSUE THREAD

**Issue by djdelorie** [fedora-ci/scratch-build-test#9]
https://pagure.io/koji/issue/4236

This test now needs to explicitly request a repo, not just wait for an implicitly requested one.

**Comment by rh-mcermak** [comment]
The testcase itself now does use koji wait-repo --request ....  However the jenkins worker apparently doesn't have fresh enough koji.  Working with OSCI folks to get this fixed.  To work this around, the request may be done manually while the automated test is running.

**Comment by rh-mcermak** [comment]
The issue is fixed IMHO.  My manual re-run passed now for glibc-2.40-11.fc41 here: https://osci-jenkins-1.ci.fedoraproject.org/job/scratch-build-test/1570/console .
